version: 2.1

orbs:
  docker: circleci/docker@2.2.0

commands:
  download-dependencies:
    description: "Download Maven dependencies and pull base Docker image"
    steps:
      - run:
          name: Download dependencies
          command: |
            mvn -B org.apache.maven.plugins:maven-dependency-plugin:3.8.1:go-offline de.qaware.maven:go-offline-maven-plugin:1.2.8:resolve-dependencies -T3
            docker pull eclipse-temurin:11.0.22_7-jdk

jobs:
  build-and-test:
    machine:
      image: ubuntu-2004:202111-02  # Includes Docker and OpenJDK 11
      resource_class: large
    environment:
      TZ: America/Los_Angeles
    steps:
      - checkout
      - download-dependencies
      - run:
          name: Build SQRL
          command: mvn -T 1 -B -U -e clean verify
          environment:
            DATASQRL_TOKEN: $DATASQRL_TOKEN
      - run:
          name: Build Docker image
          command: docker build -t sqrl-test ./sqrl-tools
      - run:
          name: Run conference tests
          command: |
            docker run -i --rm -v $PWD:/build sqrl-test test conference.sqrl conference.graphqls --snapshot snapshots-conference --tests tests-conference
          working_directory: ./sqrl-testing/sqrl-integration-tests/src/test/resources/usecases/conference
      - run:
          name: Run UDF tests
          command: |
            docker run -i --rm -v $PWD:/build sqrl-test test myudf.sqrl --snapshot snapshots-myudf --tests tests-myudf
          working_directory: ./sqrl-testing/sqrl-integration-tests/src/test/resources/usecases/udf
      - run:
          name: Check test results
          command: |
            if [ $? -ne 0 ]; then
              echo "Test failed."
              exit 1
            else
              echo "Test passed."
            fi

  latest-docker-build:
    docker:
      - image: cimg/openjdk:11.0
    environment:
      TZ: America/Los_Angeles
    steps:
      - checkout
      - download-dependencies
      - run:
          name: Build SQRL
          command: mvn -T 1 -B -U -e clean package
          environment:
            DATASQRL_TOKEN: $DATASQRL_TOKEN
      - docker/install-docker-tools
      - docker/build:
          image: datasqrl/cmd
          tag: dev
          dockerfile: sqrl-tools/Dockerfile
          path: sqrl-tools
          extra_build_args: --platform=linux/amd64,linux/arm64
      - docker/build:
          image: datasqrl/sqrl-server
          tag: dev
          dockerfile: sqrl-server/sqrl-server-vertx/Dockerfile
          path: sqrl-server/sqrl-server-vertx
          extra_build_args: --platform=linux/amd64,linux/arm64
      - docker/push:
          image: datasqrl/cmd
          tag: dev
      - docker/push:
          image: datasqrl/sqrl-server
          tag: dev

  tag-docker-build:
    docker:
      - image: cimg/openjdk:11.0
    steps:
      - checkout
      - download-dependencies
      - run:
          name: Build SQRL
          command: mvn -T 1 -B -U -e clean package -DskipTests=true
          environment:
            DATASQRL_TOKEN: $DATASQRL_TOKEN
      - docker/install-docker-tools
      - docker/build:
          image: datasqrl/cmd
          tag: "$CIRCLE_TAG,latest"
          dockerfile: sqrl-tools/Dockerfile
          path: sqrl-tools
          extra_build_args: --platform=linux/amd64,linux/arm64
      - docker/build:
          image: datasqrl/sqrl-server
          tag: "$CIRCLE_TAG,latest"
          dockerfile: sqrl-server/sqrl-server-vertx/Dockerfile
          path: sqrl-server/sqrl-server-vertx
          extra_build_args: --platform=linux/amd64,linux/arm64
      - docker/push:
          image: datasqrl/cmd
          tag: "$CIRCLE_TAG"
      - docker/push:
          image: datasqrl/cmd
          tag: latest
      - docker/push:
          image: datasqrl/sqrl-server
          tag: "$CIRCLE_TAG"
      - docker/push:
          image: datasqrl/sqrl-server
          tag: latest

workflows:
  pull-request-workflow:
    jobs:
      - build-and-test:
          context: docker-hub
          filters:
            branches:
              only: /.*/
  main-branch-workflow:
    jobs:
      - latest-docker-build:
          context: docker-hub
          filters:
            branches:
              only:
                - main
                - v0.5.9-release
  tag-workflow:
    jobs:
      - tag-docker-build:
          context: docker-hub
          filters:
            tags:
              only: /v[0-9]+(\.[0-9]+)*/
            branches:
              ignore: /.*/
