version: 2.1

orbs:
  docker: circleci/docker@2.2.0

commands:
  download-dependencies:
    description: "Download Maven dependencies and pull base Docker image"
    steps:
      - run:
          name: Download dependencies
          command: |
            mvn -B org.apache.maven.plugins:maven-dependency-plugin:3.8.1:go-offline de.qaware.maven:go-offline-maven-plugin:1.2.8:resolve-dependencies -T3
            docker pull eclipse-temurin:11.0.22_7-jdk

jobs:
  build-and-test:
    docker:
      - image: cimg/openjdk:11.0
        # Ensure Docker daemon is available
        environment:
          DOCKER_HOST: unix:///var/run/docker.sock
    # Secondary Docker service image for DinD
    # This provides the Docker daemon that Testcontainers will use
      - image: docker:20.10.24-dind
        environment:
          DOCKER_TLS_CERTDIR: "" # Disable TLS for simplicity
    environment:
      TZ: America/Los_Angeles
      # Optional: Configure Testcontainers to use the Docker daemon explicitly
      TESTCONTAINERS_HOST_OVERRIDE: localhost
    resource_class: large
    steps:
      - checkout
      - download-dependencies
      - run:
          name: Build SQRL
          command: mvn -T 1 -B -U -e clean verify
          environment:
            DATASQRL_TOKEN: $DATASQRL_TOKEN
      - run:
          name: Build Docker image
          command: docker build -t sqrl-test ./sqrl-tools
      - run:
          name: Run conference tests
          command: |
            docker run -i --rm -v $PWD:/build sqrl-test test conference.sqrl conference.graphqls --snapshot snapshots-conference --tests tests-conference
          working_directory: ./sqrl-testing/sqrl-integration-tests/src/test/resources/usecases/conference
      - run:
          name: Run UDF tests
          command: |
            docker run -i --rm -v $PWD:/build sqrl-test test myudf.sqrl --snapshot snapshots-myudf --tests tests-myudf
          working_directory: ./sqrl-testing/sqrl-integration-tests/src/test/resources/usecases/udf
      - run:
          name: Check test results
          command: |
            if [ $? -ne 0 ]; then
              echo "Test failed."
              exit 1
            else
              echo "Test passed."
            fi

  # ... (other jobs remain unchanged)

workflows:
  pull-request-workflow:
    jobs:
      - build-and-test:
          context: docker-hub
          filters:
            branches:
              only: /.*/
  main-branch-workflow:
    jobs:
      - latest-docker-build:
          context: docker 阳-hub
          filters:
            branches:
              only:
                - main
                - v0.5.9-release
  tag-workflow:
    jobs:
      - tag-docker-build:
          context: docker-hub
          filters:
            tags:
              only: /v[0-9]+(\.[0-9]+)*/
            branches:
              ignore: /.*/
